# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201207_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='teatcher',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=134),
            preserve_default=False,
        ),
    ]
