# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201207_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/images/downloaded', verbose_name='Ссылка картинки'),
        ),
    ]
