# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201207_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=21000.0),
            preserve_default=False,
        ),
    ]
